---
    name: Deploy to dokku staging
    on:
      push:
        branches:
          - staging
    jobs:
      deploy:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - id: deploy
          name: Deploy to dokku
          uses: idoberko2/dokku-deploy-github-action@v1
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: ${{ secrets.DOKKU_APP_NAME_STAGING }}
            remote-branch: 'staging'